<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tenant;
use App\Models\TenantInvite;
use Illuminate\Http\Request;

class TenantInviteController extends Controller
{
    /**
     * Store a new tenant invite generated by the Super Admin.
     */
    public function store(Request $request, Tenant $tenant)
    {
        $validated = $request->validate([
            'email' => 'required|email|max:255',
        ]);

        $invite = TenantInvite::create([
            'tenant_id' => $tenant->id,
            'email' => $validated['email'],
            'token' => TenantInvite::generateToken(),
            'expires_at' => now()->addDays(7),
        ]);

        $inviteUrl = url("/register/{$invite->token}");

        return back()->with('success', "Invite generated successfully: {$inviteUrl}");
    }
}
