<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tenant;
use App\Models\TenantInvite;
use Illuminate\Http\Request;

class TenantInviteController extends Controller
{
    /**
     * Store a new tenant invite generated by the Super Admin.
     */
    public function store(Request $request, Tenant $tenant)
    {
        $validated = $request->validate([
            'email' => [
                'required',
                'email',
                'max:255',
                function ($attribute, $value, $fail) use ($tenant) {
                    if (\App\Models\User::where('email', $value)->where('tenant_id', $tenant->id)->exists()) {
                        $fail('This user is already a member of this tenant.');
                    }
                },
                function ($attribute, $value, $fail) use ($tenant) {
                    if (TenantInvite::where('email', $value)
                        ->whereNull('accepted_at')
                        ->exists()) {
                        $fail('A pending invite already exists for this email address.');
                    }
                }
            ],
        ]);

        $invite = TenantInvite::create([
            'tenant_id' => $tenant->id,
            'email' => $validated['email'],
            'token' => TenantInvite::generateToken(),
            'expires_at' => now()->addDays(7),
        ]);

        $inviteUrl = url("/register/{$invite->token}");

        return back()->with('success', "Invite generated successfully: {$inviteUrl}");
    }
}
